import React, { useEffect, useMemo, useRef, useState } from 'react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, LabelList, PieChart, Pie, Cell } from 'recharts'
import { Archive, CalendarDays, CheckCircle2, ChevronDown, Clock3, Filter, RotateCcw, Search, TrendingUp, Users, X, AlertTriangle, Database } from 'lucide-react'

const COLORS=['#1683bd','#16a66b','#f29a23','#e23b45','#7b61c9','#1ba7a0','#db2777','#64748b','#65a30d','#ea580c']
const TERMINAIS=new Set(['ENCERRADO','ARQUIVADO','CANCELADO'])
const MESES=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
const clean=v=>v==null?'':String(v).trim()
const toDate=v=>{const s=clean(v);if(!s)return null;const iso=/^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10)+'T12:00:00':s.replace(' ','T');const d=new Date(iso);return Number.isNaN(d.getTime())?null:d}
const fmt=n=>Number(n||0).toLocaleString('pt-BR')
const pct=n=>`${Number(n||0).toFixed(1).replace('.',',')}%`
const fmtDate=v=>{const d=toDate(v);return d?d.toLocaleDateString('pt-BR'):'—'}
const fmtDateTime=v=>{const d=toDate(v);return d?d.toLocaleString('pt-BR'):'—'}
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
const days=(a,b)=>{const x=toDate(a),y=toDate(b);return x&&y?Math.max(0,Math.round((y-x)/86400000)):null}

function normalize(r){const sit=clean(r.SituacaoAtual);return {...r,CategoriaFinal:clean(r.CategoriaFinal)||'Classificação pendente',StatusOperacionalAtual:clean(r.StatusOperacionalAtual)||'Não identificado',Responsavel:clean(r.Responsavel)||'Não identificado',DiasSemMovimento:Number(r.DiasSemMovimento||0),encerrado:Boolean(clean(r.DataEncerramento))||TERMINAIS.has(sit.toUpperCase())}}
async function loadData(){const r=await fetch('/data/protocolos.json.gz',{cache:'no-store'});if(!r.ok)throw new Error(`Dados indisponíveis (${r.status})`);if(typeof DecompressionStream==='undefined')throw new Error('Navegador sem suporte à descompressão');const stream=r.body.pipeThrough(new DecompressionStream('gzip'));const rows=await new Response(stream).json();return {rows:rows.map(normalize),updated:'2026-08-20 18:58:21'}}

function MultiSelect({label,options,values,onChange}){const [open,setOpen]=useState(false),[q,setQ]=useState('');const ref=useRef(null);useEffect(()=>{const h=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false)};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[]);const shown=options.filter(x=>x.toLowerCase().includes(q.toLowerCase()));const toggle=v=>onChange(values.includes(v)?values.filter(x=>x!==v):[...values,v]);return <div ref={ref} style={{position:'relative'}}><button onClick={()=>setOpen(!open)} style={{border:'1px solid #d7e3ec',background:values.length?'#e9f6fc':'#fff',borderRadius:10,padding:'9px 11px',display:'flex',gap:7,alignItems:'center',fontWeight:750,color:'#315067'}}>{label}{values.length>0&&<b style={{background:'#0b6d9d',color:'#fff',borderRadius:20,minWidth:20,height:20,display:'grid',placeItems:'center',fontSize:10}}>{values.length}</b>}<ChevronDown size={14}/></button>{open&&<div style={{position:'absolute',zIndex:40,top:44,left:0,width:320,maxHeight:410,background:'#fff',border:'1px solid #d7e3ec',borderRadius:12,boxShadow:'0 18px 45px #17324a30',padding:10}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><strong style={{fontSize:12}}>{label}</strong>{values.length>0&&<button onClick={()=>onChange([])} style={{border:0,background:'none',color:'#0b6d9d'}}>Limpar</button>}</div><div style={{display:'flex',alignItems:'center',gap:6,border:'1px solid #dfe8ef',borderRadius:8,padding:7,marginBottom:7}}><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Pesquisar...' style={{border:0,outline:0,width:'100%'}}/></div><div style={{overflow:'auto',maxHeight:300}}>{shown.map(v=><label key={v} style={{display:'flex',gap:8,padding:'7px 4px',fontSize:12}}><input type='checkbox' checked={values.includes(v)} onChange={()=>toggle(v)}/><span>{v}</span></label>)}</div></div>}</div>}

function Kpi({icon:Icon,label,value,sub,tone,onClick}){return <button className={`kpi ${tone}`} onClick={onClick}><div className='kpiIcon'><Icon size={19}/></div><div className='kpiText'><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></button>}
function Panel({title,tag,children,className=''}){return <section className={`panel ${className}`}><div className='panelHead'><div><span>{tag}</span><h3>{title}</h3></div></div>{children}</section>}
function group(rows,key,limit=12){const m=new Map();rows.forEach(r=>{const k=clean(r[key])||'Não identificado';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([name,value])=>({name,value}))}
function Drawer({data,onClose}){if(!data)return null;return <div className='overlay' onMouseDown={onClose}><div className='drawer' onMouseDown={e=>e.stopPropagation()}><div className='drawerHead'><div><small>DRILL-DOWN</small><h2>{data.title}</h2><p>{fmt(data.rows.length)} protocolos</p></div><button onClick={onClose}>×</button></div><div className='tableWrap tall'><table><thead><tr><th>Protocolo</th><th>Abertura</th><th>Categoria</th><th>Status</th><th>Responsável</th><th>Sem movimento</th><th>Inscrição</th></tr></thead><tbody>{data.rows.slice(0,600).map(r=><tr key={r.ProtocoloID}><td className='mono'>{r.NumeroAnoOriginal||r.ProtocoloID}</td><td>{fmtDate(r.DataAbertura)}</td><td>{r.CategoriaFinal}</td><td>{r.StatusOperacionalAtual}</td><td>{r.Responsavel}</td><td className={r.DiasSemMovimento>60?'critical':r.DiasSemMovimento>30?'warning':''}>{r.DiasSemMovimento} d</td><td className='mono'>{r.InscricaoImobiliaria||'—'}</td></tr>)}</tbody></table></div></div></div>}

export default function App(){
 const [data,setData]=useState([]),[updated,setUpdated]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');const [cats,setCats]=useState([]),[stats,setStats]=useState([]),[owners,setOwners]=useState([]),[from,setFrom]=useState('2026-01-01'),[to,setTo]=useState('2026-08-20'),[threshold,setThreshold]=useState(30),[topN,setTopN]=useState(10),[query,setQuery]=useState(''),[drawer,setDrawer]=useState(null)
 useEffect(()=>{loadData().then(x=>{setData(x.rows);setUpdated(x.updated)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const catOpts=useMemo(()=>[...new Set(data.map(r=>r.CategoriaFinal))].sort(),[data]);const statOpts=useMemo(()=>[...new Set(data.map(r=>r.StatusOperacionalAtual))].sort(),[data]);const ownerOpts=useMemo(()=>[...new Set(data.map(r=>r.Responsavel))].sort(),[data])
 const dimensional=useMemo(()=>data.filter(r=>(!cats.length||cats.includes(r.CategoriaFinal))&&(!stats.length||stats.includes(r.StatusOperacionalAtual))&&(!owners.length||owners.includes(r.Responsavel))&&(!query||[r.ProtocoloID,r.NumeroAnoOriginal,r.CategoriaFinal,r.StatusOperacionalAtual,r.Responsavel,r.InscricaoImobiliaria].some(v=>clean(v).toLowerCase().includes(query.toLowerCase())))),[data,cats,stats,owners,query])
 const start=toDate(from),end=toDate(to);const inRange=v=>{const d=toDate(v);return d&&(!start||d>=start)&&(!end||d<=end)}
 const recebidos=useMemo(()=>dimensional.filter(r=>inRange(r.DataAbertura)),[dimensional,from,to]);const concluidos=useMemo(()=>dimensional.filter(r=>r.DataEncerramento&&inRange(r.DataEncerramento)),[dimensional,from,to]);const estoque=useMemo(()=>dimensional.filter(r=>!r.encerrado),[dimensional]);const parados=useMemo(()=>estoque.filter(r=>r.DiasSemMovimento>threshold),[estoque,threshold]);const tempos=useMemo(()=>concluidos.map(r=>days(r.DataAbertura,r.DataEncerramento)).filter(v=>v!=null),[concluidos]);const media=tempos.length?Math.round(tempos.reduce((a,b)=>a+b,0)/tempos.length):0,med=Math.round(median(tempos))
 const monthly=useMemo(()=>{const m=new Map();const add=(r,field,k)=>{const d=toDate(r[field]);if(!d)return;const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(!m.has(key))m.set(key,{key,label:`${MESES[d.getMonth()]}/${String(d.getFullYear()).slice(-2)}`,recebidos:0,concluidos:0});m.get(key)[k]++};recebidos.forEach(r=>add(r,'DataAbertura','recebidos'));concluidos.forEach(r=>add(r,'DataEncerramento','concluidos'));return [...m.values()].sort((a,b)=>a.key.localeCompare(b.key))},[recebidos,concluidos])
 const aging=useMemo(()=>[{name:'0–15',value:estoque.filter(r=>r.DiasSemMovimento<=15).length,min:0,max:15},{name:'16–30',value:estoque.filter(r=>r.DiasSemMovimento>=16&&r.DiasSemMovimento<=30).length,min:16,max:30},{name:'31–60',value:estoque.filter(r=>r.DiasSemMovimento>=31&&r.DiasSemMovimento<=60).length,min:31,max:60},{name:'61–90',value:estoque.filter(r=>r.DiasSemMovimento>=61&&r.DiasSemMovimento<=90).length,min:61,max:90},{name:'91–120',value:estoque.filter(r=>r.DiasSemMovimento>=91&&r.DiasSemMovimento<=120).length,min:91,max:120},{name:'>120',value:estoque.filter(r=>r.DiasSemMovimento>120).length,min:121,max:99999}],[estoque]);const catData=useMemo(()=>group(estoque,'CategoriaFinal',topN),[estoque,topN]);const statData=useMemo(()=>group(estoque,'StatusOperacionalAtual',10),[estoque]);const ownerData=useMemo(()=>group(estoque,'Responsavel',topN).map(x=>({...x,criticos:estoque.filter(r=>r.Responsavel===x.name&&r.DiasSemMovimento>threshold).length})),[estoque,topN,threshold])
 const toggleCat=n=>setCats(v=>v.includes(n)?v.filter(x=>x!==n):[...v,n]);const toggleStat=n=>setStats(v=>v.includes(n)?v.filter(x=>x!==n):[...v,n]);const reset=()=>{setCats([]);setStats([]);setOwners([]);setFrom('2026-01-01');setTo('2026-08-20');setThreshold(30);setQuery('');setTopN(10)}
 if(loading)return <div className='loading'><div className='spinner'/><h2>Carregando BI SEPLAN</h2><p>Processando a base 2025+</p></div>;if(error)return <div className='loading error'><AlertTriangle/><h2>Falha ao carregar o BI</h2><p>{error}</p></div>
 return <div><div className='brandStripe'><span/><span/></div><header className='topbar'><div className='brandWrap'><img className='logo' src='/logo-itapoa.png'/><div><div className='eyebrow'>SECRETARIA DE PLANEJAMENTO</div><h1>Gestão à Vista <span>SEPLAN</span></h1><p>Indicadores operacionais e gerenciais</p></div></div><div className='baseBox'><span>Base atualizada</span><strong>{fmtDateTime(updated)}</strong><small>{fmt(data.length)} protocolos · 2025+</small></div></header><main>
 <div className='filtersPanel'><div className='filterGroup'><label>Período inicial</label><input type='date' value={from} onChange={e=>setFrom(e.target.value)} style={{border:'1px solid #d7e3ec',borderRadius:10,padding:'9px 10px'}}/></div><div className='filterGroup'><label>Período final</label><input type='date' value={to} onChange={e=>setTo(e.target.value)} style={{border:'1px solid #d7e3ec',borderRadius:10,padding:'9px 10px'}}/></div><div className='filterGroup'><label>Seleção múltipla</label><MultiSelect label='Categorias' options={catOpts} values={cats} onChange={setCats}/></div><div className='filterGroup'><label>Seleção múltipla</label><MultiSelect label='Status' options={statOpts} values={stats} onChange={setStats}/></div><div className='filterGroup'><label>Seleção múltipla</label><MultiSelect label='Responsável' options={ownerOpts} values={owners} onChange={setOwners}/></div><div className='filterGroup wide'><label>Busca</label><div style={{display:'flex',alignItems:'center',gap:6,border:'1px solid #d7e3ec',borderRadius:10,padding:'8px 10px'}}><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Protocolo, inscrição...' style={{border:0,outline:0}}/></div></div><button className='clearBtn' onClick={reset}><RotateCcw size={14}/> Limpar filtros</button></div>
 <div className='sectionTitle'><div><span>INDICADORES DA BASE ATUAL</span><h2>Visão executiva</h2></div><div className='threshold'><span>Processo parado:</span>{[15,30,60,90,120].map(n=><button key={n} className={threshold===n?'active':''} onClick={()=>setThreshold(n)}>{n}d</button>)}</div></div>
 <div className='kpiGrid'><Kpi icon={TrendingUp} label='Processos recebidos' value={fmt(recebidos.length)} sub='aberturas no período selecionado' tone='blue' onClick={()=>setDrawer({title:'Recebidos no período',rows:recebidos})}/><Kpi icon={CheckCircle2} label='Processos concluídos' value={fmt(concluidos.length)} sub='encerramentos no período selecionado' tone='green' onClick={()=>setDrawer({title:'Concluídos no período',rows:concluidos})}/><Kpi icon={Archive} label='Estoque pendente' value={fmt(estoque.length)} sub='posição atual da base' tone='orange' onClick={()=>setDrawer({title:'Estoque pendente',rows:estoque})}/><Kpi icon={Clock3} label='Tempo médio' value={tempos.length?`${media} dias`:'—'} sub={tempos.length?`mediana: ${med} dias`:'sem encerramentos no recorte'} tone='purple'/><Kpi icon={AlertTriangle} label={`Parados > ${threshold} dias`} value={pct(estoque.length?parados.length/estoque.length*100:0)} sub={`${fmt(parados.length)} de ${fmt(estoque.length)} pendentes`} tone='red' onClick={()=>setDrawer({title:`Parados > ${threshold} dias`,rows:parados})}/></div>
 <div className='insightRow'><div><span>Saldo do período</span><strong className={recebidos.length-concluidos.length>0?'bad':'good'}>{recebidos.length-concluidos.length>0?'+':''}{fmt(recebidos.length-concluidos.length)}</strong><small>recebidos − concluídos</small></div><div><span>Taxa de conclusão</span><strong>{pct(recebidos.length?concluidos.length/recebidos.length*100:0)}</strong><small>indicador descritivo do período</small></div><div><span>Criticidade do estoque</span><strong className='bad'>{pct(estoque.length?parados.length/estoque.length*100:0)}</strong><small>sem movimentação acima do limite escolhido</small></div></div>
 <div className='layout'>
  <Panel title='Recebidos × concluídos' tag='FLUXO MENSAL' className='wide'><div style={{height:330}}><ResponsiveContainer width='100%' height='100%'><BarChart data={monthly} margin={{top:28,right:12,left:0,bottom:0}}><CartesianGrid strokeDasharray='3 3' vertical={false}/><XAxis dataKey='label'/><YAxis allowDecimals={false}/><Tooltip formatter={v=>fmt(v)}/><Legend/><Bar dataKey='recebidos' name='Recebidos' fill='#1683bd' radius={[5,5,0,0]}><LabelList dataKey='recebidos' position='top' formatter={fmt}/></Bar><Bar dataKey='concluidos' name='Concluídos' fill='#16a66b' radius={[5,5,0,0]}><LabelList dataKey='concluidos' position='top' formatter={fmt}/></Bar></BarChart></ResponsiveContainer></div></Panel>
  <Panel title='Estoque por categoria' tag='CLIQUE PARA FILTRAR'><div style={{display:'flex',justifyContent:'flex-end',marginBottom:5}}><select value={topN} onChange={e=>setTopN(Number(e.target.value))}>{[8,10,15,20].map(n=><option key={n} value={n}>Top {n}</option>)}</select></div><div style={{height:390}}><ResponsiveContainer width='100%' height='100%'><BarChart data={catData} layout='vertical' margin={{left:8,right:35}}><CartesianGrid strokeDasharray='3 3' horizontal={false}/><XAxis type='number' hide/><YAxis dataKey='name' type='category' width={185} tick={{fontSize:10}}/><Tooltip formatter={v=>fmt(v)}/><Bar dataKey='value' fill='#1683bd' radius={[0,6,6,0]} onClick={d=>toggleCat(d.name)} cursor='pointer'><LabelList dataKey='value' position='right' formatter={fmt}/></Bar></BarChart></ResponsiveContainer></div></Panel>
  <Panel title='Status do estoque' tag='CLIQUE PARA FILTRAR'><div style={{height:390}}><ResponsiveContainer width='100%' height='100%'><PieChart><Pie data={statData} dataKey='value' nameKey='name' innerRadius={60} outerRadius={94} paddingAngle={2} onClick={d=>toggleStat(d.name)} cursor='pointer'><LabelList dataKey='value' position='outside' formatter={fmt}/>{statData.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={v=>fmt(v)}/><Legend layout='vertical' verticalAlign='middle' align='right' wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer></div></Panel>
  <Panel title='Tempo sem movimentação' tag='AGING DO ESTOQUE'><div style={{height:300}}><ResponsiveContainer width='100%' height='100%'><BarChart data={aging} margin={{top:25,right:12,left:0,bottom:0}}><CartesianGrid strokeDasharray='3 3' vertical={false}/><XAxis dataKey='name'/><YAxis allowDecimals={false}/><Tooltip formatter={v=>fmt(v)}/><Bar dataKey='value' fill='#f29a23' radius={[5,5,0,0]} onClick={d=>setDrawer({title:`Sem movimentação · ${d.name} dias`,rows:estoque.filter(r=>r.DiasSemMovimento>=d.min&&r.DiasSemMovimento<=d.max)})} cursor='pointer'><LabelList dataKey='value' position='top' formatter={fmt}/></Bar></BarChart></ResponsiveContainer></div></Panel>
  <Panel title='Pendências por responsável' tag='GARGALOS' className='wide'><div style={{height:420}}><ResponsiveContainer width='100%' height='100%'><BarChart data={ownerData} layout='vertical' margin={{left:10,right:38}}><CartesianGrid strokeDasharray='3 3' horizontal={false}/><XAxis type='number'/><YAxis dataKey='name' type='category' width={220} tick={{fontSize:10}}/><Tooltip formatter={(v,n)=>[fmt(v),n==='criticos'?`>${threshold} dias`:'Estoque']}/><Legend/><Bar dataKey='value' name='Estoque' fill='#1ba7a0' radius={[0,5,5,0]} onClick={d=>setOwners([d.name])} cursor='pointer'><LabelList dataKey='value' position='right' formatter={fmt}/></Bar><Bar dataKey='criticos' name={`>${threshold} dias`} fill='#e23b45' radius={[0,5,5,0]}><LabelList dataKey='criticos' position='right' formatter={fmt}/></Bar></BarChart></ResponsiveContainer></div></Panel>
 </div>
 <section className='panel full' style={{marginTop:14}}><div className='searchHead'><div><span>DRILL-DOWN</span><h2>Explorador de processos</h2></div><div className='resultCount'>{fmt(dimensional.length)} registros no recorte dimensional</div></div><div className='tableWrap'><table><thead><tr><th>Protocolo</th><th>Abertura</th><th>Categoria</th><th>Status</th><th>Responsável</th><th>Sem movimento</th><th>Inscrição</th></tr></thead><tbody>{dimensional.slice(0,150).map(r=><tr key={r.ProtocoloID} onClick={()=>setDrawer({title:r.NumeroAnoOriginal||r.ProtocoloID,rows:[r]})}><td className='mono'>{r.NumeroAnoOriginal||r.ProtocoloID}</td><td>{fmtDate(r.DataAbertura)}</td><td>{r.CategoriaFinal}</td><td>{r.StatusOperacionalAtual}</td><td>{r.Responsavel}</td><td className={r.DiasSemMovimento>60?'critical':r.DiasSemMovimento>30?'warning':''}>{r.DiasSemMovimento} d</td><td className='mono'>{r.InscricaoImobiliaria||'—'}</td></tr>)}</tbody></table></div></section>
 </main><footer><Database size={12}/> Fonte oficial: base SEPLAN 2025+ · visualização sanitizada para BI</footer><Drawer data={drawer} onClose={()=>setDrawer(null)}/></div>
}
